import type { Metadata } from "next";
import "./globals.css";
import ConvexClientProvider from "@/components/ConvexClientProvider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/convex.svg",
  },
};

const satoshi = localFont({
  src: [
    {
      path: "../public/fonts/Satoshi/Satoshi-Variable.woff2",
      weight: "100 900", // Define the variable font weight range
      style: "normal",
    },
    {
      path: "../public/fonts/Satoshi/Satoshi-Variable.woff",
      weight: "100 900",
      style: "normal",
    },
    {
      path: "../public/fonts/Satoshi/Satoshi-Variable.ttf",
      weight: "100 900",
      style: "normal",
    },
    {
      path: "../public/fonts/Satoshi/Satoshi-VariableItalic.woff2",
      weight: "100 900",
      style: "italic",
    },
    {
      path: "../public/fonts/Satoshi/Satoshi-VariableItalic.woff",
      weight: "100 900",
      style: "italic",
    },
    {
      path: "../public/fonts/Satoshi/Satoshi-VariableItalic.ttf",
      weight: "100 900",
      style: "italic",
    },
  ],
  display: "swap",
  variable: "--font-satoshi",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${satoshi.variable} antialiased`}>
        <ClerkProvider dynamic>
          <ConvexClientProvider>{children}</ConvexClientProvider>
        </ClerkProvider>

        <Toaster />
      </body>
    </html>
  );
}
